### ISSUE TITLE
Verify that dashboard views conform to new schema

### ISSUE THREAD

**Issue by erikor** [JovingeLabSoftware/CouchLincs#15]
Schema has changed slightly to improve field naming and capture documnt types.  May need to update views used by the dashboard:

Schema for instances:
```
{
   metadata: {...},
   gene_ids: [...],
   type: {...} // should be "q2norm" for level 2 instances
   data: [...]
}

Schema for calculated perturbation scores (e.g. z-scores):
```
{
   cell: "...",
   perturbagen: "...",
   dose: 999,
   duration: 999,
   type: "..." // should be "zscore" for zscores 
   method: "..." // should be "zsvc_plate" for zscores from same plate vehicle controls 
   gene_ids: [...],
   data: [...],
   gold: true/false
}

**Comment by borgmaan** [comment]
Is our `metadata` stored differently now than it was before? None of the views seem to be working. I can emit *all* the `metadata` with something like this:

```
function (doc, meta)  {
  emit(doc.metadata, null);
}
```

But whenever I try to access a specific item in the metadata, it only returns `null`. Ex:

```
function (doc, meta) {
  emit(doc.metadata.cell_id, null);
}
```

All other views seem to be having the same issue. Is the `metadata` in our `doc` different in some way? Here is what it looks like now:

```
 "metadata": [
       {
           "distil_id": "PCLB003_MCF7_24H_X1_B13:H16",
           "pert_id": "BRD-K17953061",
           "pert_desc": "-666",
           "cell_id": "MCF7",
           "pert_time": 24,
           "pert_time_unit": "h",
           "pert_dose": 0.37,
           "pert_dose_unit": "um",
           "pert_type": "trt_cp",
           "pert_vehicle": "DMSO",
           "is_gold": true
       }
   ]
```

**Comment by erikor** [comment]
Pfffffffffffttttttttttttttththththbbttt... . .

Looks like I created Metadata as an array with one element which contains the JSON.  So you would need:

```
emit(doc.metadata[0].cell_id, null)
```
That is obviously broken.  Will fix with next data re-up.  In the mean time, you can plan for both the current and the correct format like this:

```JavaScript
function (doc, meta) {
  if(doc.metadata.length) {
    emit(doc.metadata[0].cell_id, null);
  } else {
    emit(doc.metadata.cell_id, null);
  }
}
```

**Comment by borgmaan** [comment]
Ok - that makes sense. Thanks!

**Comment by borgmaan** [comment]
Dashboard working fine after patching views with your suggestion.
