### ISSUE TITLE
slinky calc function needs to conform to new schema

### ISSUE THREAD

**Issue by erikor** [JovingeLabSoftware/CouchLincs#16]
see issue #15 for details on schema

**Comment by borgmaan** [comment]
`Slinky$calc()` has been updated to work with the new schema on [this branch](https://github.com/JovingeLabSoftware/CouchLincs/tree/z-score-update). Everything appears to be working except for saving the document back on the `/LINCS/pert` endpoint. You can see my attempt in `Slinky$saveZ()` but that is hanging and not saving the document at the moment. I will continue to debug today.

**Comment by borgmaan** [comment]
closed by #27
