### ISSUE TITLE
CouchLincs REST server cannot reach cluster in different region

### ISSUE THREAD

**Issue by erikor** [JovingeLabSoftware/CouchLincs#24]
We have set up a new cluster in the us-west-2 region so we can use EFS.  However, now when I try to hit coucbase there I get:

The discussion here: https://forums.couchbase.com/t/timeout-errors/1215 suggests the issue is that the node couchbase SDK client is getting tripped up by the fact that the couchbase nodes have internal IPs which cannot be accessed from the outside (**despite the fact that we are connecting via the master's public IP address, and I can access couchbase and its web interface -- including view queries -- via the public IP without difficulty, just like the original poster in that discussion**).

So we probably need to recreate the couchbase cluster using fully qualified domain names (FQDN) which should then transparently map to private IPs on call inside of the server's EC2 region, and public IPs for calls outside of the region.

**Comment by borgmaan** [comment]
All patched and data is being uploaded now. Solution was to use each instance's EC2 Public DNS name as the node's hostname during Couchbase setup. It is also necessary to open up ports 11210 and 11211 in the `@sc-couchstar` security group.
