### ISSUE TITLE
Validate zscore calculation

### ISSUE THREAD

**Issue by erikor** [JovingeLabSoftware/CouchLincs#30]
Recalculate some zscores out of q2norm data file in /mnt/lincs/LINCStest and ensure they exactly match zscores on couchbase

**Comment by borgmaan** [comment]
Overwhelming success!

<img width="730" alt="screen shot 2015-12-16 at 7 29 28 pm" src="https://cloud.githubusercontent.com/assets/1987666/11858149/f4c9b45c-a42c-11e5-8768-7f46d155d512.png">
