### ISSUE TITLE
Need JLabSW AMI for cluster

### ISSUE THREAD

**Issue by erikor** [JovingeLabSoftware/CouchLincs#6]
Need to obtain the star cluster AMI and update with our R dependencies and perhaps try to upgrade ubuntu.

Should probably still pull slinky from github at boot up to make sure it stays up to date as we are actively developing that package.

**Comment by borgmaan** [comment]
See blog post [here](http://jovingelabsoftware.github.io/blog/2015/12/07/creating-a-custom-ami-for-starcluster/)

`devtools` is the only R package I am installing for now. I figure we will want the most recent version of anything else we add (and we might want to refresh `devtools` on launch anyway)

**Comment by erikor** [comment]
I think we also need a script to pass to USERDATA_SCRIPTS to install slinky at startup, right?  Or did I miss that part?

Nice blog post.

**Comment by borgmaan** [comment]
The scripts passed to USERDATA_SCRIPTS live on your local machine and are separate from the AMI. You add the local paths to the files to your StarCluster config. [Here](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html#user-data-shell-scripts) are the related AWS docs.

I could add an `init.d` script to the AMI that would install `slinky` and `ExpSpect` from our GitHub repositories on launch. Or we could keep project specific standardized scripts to pass to USERDATA_SCRIPTS in each repo. Either approach seems fine to me.

**Comment by erikor** [comment]
Ah. I didn't understand that USERDATA_SCRIPTS get sent over the wire...assumed they were local on each machine. Great then. You can reclose :)

**Comment by erikor** [comment]
assigned points and reclosed
