### ISSUE TITLE
Identify appropriate controls for LINCS RNA reagents

### ISSUE THREAD

**Issue by erikor** [JovingeLabSoftware/CouchLincs#7]
There are several different types of controls for genetic perturbagens on LINCS.  We need to decide which one(s) to use when calculating Z-scores for these.

**Comment by borgmaan** [comment]
Decided to use same plate `ctl_vector` samples as controls. REST endpoint to access IDs of the controls give a plate, cell line, and timepoint was added in 2fc8fde
